/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LoginBeanTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("Dummy test, allways successfull", true);
    }
}
